version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - restore_cache:
          key: cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}

      - checkout

      - run: cargo check --workspace
      - run: cargo test --workspace
      - run: cargo build --workspace

      - save_cache:
          key: cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
            - target
