version: "2.1"

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: sleep 10

# this pipeline is impacted by https://github.com/CircleCI-Public/rust-orb/issues/18 and the fact
# that the orb doesn't support workspaces. Luckily we only need it for testing webhook delivery.
orbs:
  rust: circleci/rust@1.6.0
workflows:
  production:
    jobs:
      - rust/lint-test-build:
          version: "1.63.0"
      - test: {}
