version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout

      - run:
          name: test1
          command: |
            set +e
            env | sort
            cat $CIRCLE_INTERNAL_TASK_DATA
            echo ======
            cat $CIRCLE_INTERNAL_CONFIG
            echo 'export TRACEPARENT=testdata' >> "$BASH_ENV"
      - run:
          name: test2
          command: |
            set +e
            env | sort
            cat $CIRCLE_INTERNAL_TASK_DATA
            echo ======
            cat $CIRCLE_INTERNAL_CONFIG

      - restore_cache:
          key: cargo-{{ checksum "Cargo.lock" }}

      - run: cargo check --workspace
      # - run: cargo install cargo-nextest
      - run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      # - run: cargo install circleci-junit-fix
      - run: curl -sSL https://github.com/conradludgate/circleci-junit-fix/releases/download/v0.2.0/circleci-junit-fix-v0.2.0-x86_64-unknown-linux-gnu.tar.gz | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - run: cargo nextest run --workspace --profile ci
      - run: cargo test --workspace --doc
      - run: cargo build --workspace

      - run: cat target/nextest/ci/junit.xml | circleci-junit-fix > fixed-report.xml
      - store_test_results:
          path: fixed-report.xml

      - save_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
            - target
