version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - run: curl "$HOOK_URL/traceparent/$CIRCLE_WORKFLOW_ID/CIRCLE_WORKFLOW_JOB_ID" >> "$BASH_ENV"
      - run:
          name: test otel-cli
          command: |
            curl -L https://github.com/equinix-labs/otel-cli/releases/download/v0.0.20/otel-cli-0.0.20-Linux-x86_64.tar.gz | sudo tar xvzf - -C /usr/local/bin
            otel-cli exec --service my-service --name "curl google" curl https://google.com

      - checkout

      - restore_cache:
          key: cargo-{{ checksum "Cargo.lock" }}

      - run: cargo check --workspace
      # - run: cargo install cargo-nextest
      - run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      # - run: cargo install circleci-junit-fix
      - run: curl -sSL https://github.com/conradludgate/circleci-junit-fix/releases/download/v0.2.0/circleci-junit-fix-v0.2.0-x86_64-unknown-linux-gnu.tar.gz | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - run: cargo nextest run --workspace --profile ci
      - run: cargo test --workspace --doc
      - run: cargo build --workspace

      - run: cat target/nextest/ci/junit.xml | circleci-junit-fix > fixed-report.xml
      - store_test_results:
          path: fixed-report.xml

      - save_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
            - target
